DatabaseTypeORM:
  Type: "mysql"
  Host: "localhost"
  Port: 3306
  UserName: PetTester
  Password: Pa55word
  DatabaseName: petstore

api:
  listenPort: 10010
  enableKeycloakAuthorization: true

export:
  timezone: Australia/Sydney